CREATE TABLE CELULARES(
    ID_CELULAR NUMBER,
    MARCA NVARCHAR2(50),
    MODELO NVARCHAR2(50),
    COLOR NVARCHAR2(50),
    PRECIO NUMBER,
    CONSTRAINT CELULARES_PK PRIMARY KEY (ID_CELULAR)
);
--DELETE FROM CELULARES;
--MIRANDA
INSERT INTO CELULARES VALUES(1,'SAMSUNG','GALAXY S22','BLANCO',15000);
INSERT INTO CELULARES VALUES(2,'HUAWEI','P30 LITE','AZUL',20000);
INSERT INTO CELULARES VALUES(3,'XIAOMI','POCO','NEGRO',13000);
--DIANA
INSERT INTO CELULARES VALUES(4,'MOTOROLA','MOTO G14',NULL,25000);
INSERT INTO CELULARES VALUES(5,'SAMSUNG','A54 G5','VIOLETA',3000);
INSERT INTO CELULARES VALUES(6,'XIAOMI','REDMI 12',NULL,45000);
--CARLOS
INSERT INTO CELULARES VALUES(7,'OPPO','RENO 11 5G',NULL,22000);
INSERT INTO CELULARES VALUES(8,'MOTOROLA','MOTO G 53','NEGRO',5600);
INSERT INTO CELULARES VALUES(9,'HUAWEI','HONOR X8','AZUL',3600);
--CLAUDIA
INSERT INTO CELULARES VALUES(10, 'MOTOROLA', 'RAZR 40 ULTRA', 'AZUL GLACIAR',13390);
INSERT INTO CELULARES VALUES(11, 'OPPO', 'RENO 7', 'NEGRO', 19999);
INSERT INTO CELULARES VALUES(12, 'HUAWEI', 'P60 PRO', NULL, 20499);
--MARCO
INSERT INTO CELULARES VALUES(13,'MOTOROLA','EDGE 20','GRIS',10000);
INSERT INTO CELULARES VALUES(14,'APPLE','IPHONE 13','AZUL',15000);
INSERT INTO CELULARES VALUES(15,'SAMSUNG','FLIP 5','ROSA',13000);
--JAIME
INSERT INTO CELULARES VALUES(16,'APPLE','IPHONE 12','PLATEADO',7000);
INSERT INTO CELULARES VALUES(17,'HUAWEI','P40 PRO','AZUL',7300);
INSERT INTO CELULARES VALUES(18,'GOOGLE','PIXEL 5','VERDE',4300);

SELECT*FROM CELULARES;
COMMIT;

-- 1.- MOSTRAR LA INFORMACION DE LA TABLA ORDENADA DE MAYOR A MENOR EN BASE A SU PRECIO,
-- ADEMAS AGREGAR UN FORMATO AL PRECIO.
SELECT MARCA,MODELO,COLOR,
TO_CHAR(PRECIO,'$999,999.99') AS PRECIO_F FROM CELULARES ORDER BY PRECIO DESC;

-- 2.- BUSCAR LOS CELULARES QUE EN EL MODELO CONTENGAN LA LETRA X, SACAR EL PROMEDIO DEL PRECIO Y DARLE UN FORMATO
SELECT TO_CHAR(AVG(PRECIO),'$999,999.99') AS PROMEDIO FROM CELULARES
WHERE MODELO LIKE '%X%';

-- 3.- MOSTRAR LOS CELULARES QUE CUESTEN MENOS DE $15 MIL
SELECT*FROM CELULARES
WHERE PRECIO<15000;

-- 4.- CONSULTAR LOS REGISTROS QUE NO SEAN NULO, QUE SU PRECIO SEA MAYOR A 20 MIL Y ORDENARLO DE MENOR A MAYOR.
SELECT *FROM CELULARES
WHERE COLOR IS NULL AND PRECIO> 20000 ORDER BY PRECIO;

-- 5.- MOSTRAR LOS CELULARES QUE SU PRECIO SEA MAYOR A 15 MIL Y MENOR A 20000 MIL CON FORMATO
SELECT MARCA,MODELO,TO_CHAR(PRECIO,'$999,999.99') AS PRECIO_F FROM CELULARES
WHERE PRECIO>15000 AND PRECIO<20000;

-- 6.- BUSCAR LOS CELULARES DE COLOR NEGRO, FORMATO AL PRECIO Y LE CONCATENO 'PESOS MX'
SELECT MARCA,MODELO,COLOR,
TO_CHAR(PRECIO,'$999,999.99')||' PESOS MX' AS PRECIOFORMATO FROM CELULARES
WHERE COLOR='NEGRO';

-- 7.- CONTAR CUANTOS CELULARES TENGO DE CADA MARCA
SELECT MARCA,
COUNT(MARCA) AS TOTAL_MARCA FROM CELULARES GROUP BY MARCA;

-- 8.- MOSTRAR EL REGISTRO QUE TENGA EL PRECIO MAS ALTO Y DAR FORMATO
SELECT MARCA,MODELO,TO_CHAR(PRECIO,'$999,999.99') AS PRECIO FROM CELULARES WHERE PRECIO=(SELECT MAX(PRECIO) FROM CELULARES);
SELECT MARCA,MODELO, TO_CHAR(PRECIO,'$999,999.99') AS PRECIO_F FROM CELULARES ORDER BY PRECIO DESC FETCH FIRST 1 ROWS ONLY;

-- 9.- MOSTRAR EL REGISTRO QUE TENGA EL PRECIO MAS BAJO Y DAR FORMATO
SELECT MARCA,MODELO,TO_CHAR(PRECIO,'$999,999.99') AS PRECIO FROM CELULARES WHERE PRECIO=(SELECT MIN(PRECIO) FROM CELULARES);

-- 10.- DESGLOSAR EL DETALLE DE LOS CELULARES EN UNA SOLA COLUMNA.
SELECT 'MARCA:' || MARCA || ' MODELO:' || MODELO || ' COLOR:' || COLOR || ' PRECIO:' || PRECIO AS DATOS_CELULAR
FROM CELULARES;